### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors

### ISSUE THREAD

**Issue by thangarajbluescape** [sysadmind/awsses_exporter#2]
time="2020-08-16T07:10:28Z" level=error msg="Failed to get sending quota from region us-east-1: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" source="collector.go:77"
I have verified my aws credentials. AWS CLI working fine.

@sysadmind Can you please check this issue?

**Comment by sysadmind** [comment]
Are you running inside a docker container? If so, have you passed your AWS credentials into the container? They don't automatically get passed in. You have to pass via environment vars or mounting your credentials file, etc.

**Comment by thangarajbluescape** [comment]
Yes, Got it @sysadmind . It's my bad not mount credentials in docker container.
